package dev.swanhtet.godaung.model;

public enum CATEGORY {
  ELECTRONICS,
  APPAREL_AND_FASHION,
  HOME_AND_FURNITURE,
  HEALTH_AND_BEAUTY,
  AUTOMOTIVE,
  FOOD_AND_BEVERAGES,
  TOYS_AND_GAMES,
  SPORTS_AND_OUTDOORS,
  BOOKS_AND_MEDIA,
  OFFICE_SUPPLIES_AND_STATIONERY
}
